import { Chess } from 'chess.js'; //PACKAGE HANDLES LEGAL MOVES AND BOARD STATE

//KINGS VALUE SET TO ZERO, SINCE VALUE IS BASICALLY INFINITE THE EVALUATIONS WOULD MALFUNCTION IS AN EXTREMELY HIGH NUMBER WAS PLACED
//CHECKMATE DETECTION WILL BE HANDLED DIFFERENTLY LATER
const VALUES = { p:100, n:320, b:330, r:500, q:900, k:0 }; //PAWNS, KNIGHTS, BISHOPS, ROOK, QUEEN, KING
